# Generated by Django 3.1.2 on 2020-10-23 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='clase',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='clase',
            name='codigo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('estado', models.CharField(max_length=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.objeto')),
            ],
        ),
    ]
