# Generated by Django 3.1.2 on 2020-10-23 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20201023_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.articulo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
