# Generated by Django 3.1.2 on 2020-10-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=100)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.edificio')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.piso')),
            ],
        ),
    ]
