# Generated by Django 3.1.2 on 2020-10-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_edificio_piso_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='edificio',
        ),
    ]
