# Generated by Django 3.1.2 on 2020-10-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_remove_sala_edificio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='edificio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.edificio'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='objeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.objeto'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='piso',
            field=models.ForeignKey(limit_choices_to=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.edificio'), null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.piso'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='sala',
            field=models.ForeignKey(limit_choices_to=models.ForeignKey(limit_choices_to=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.edificio'), null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.piso'), null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.sala'),
        ),
    ]
