# Generated by Django 3.1.2 on 2020-10-29 14:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20201029_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='piso',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='edificio', chained_model_field='edificio', null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.piso'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='sala',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='piso', chained_model_field='piso', null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.sala'),
        ),
    ]
