# Generated by Django 3.1.2 on 2020-10-29 14:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20201029_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.tipo'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='objeto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tipo', chained_model_field='tipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.objeto'),
        ),
    ]
