# Generated by Django 3.1.2 on 2020-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20201029_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='edificio',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sala',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
