# Generated by Django 3.1.2 on 2020-11-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_auto_20201102_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
