# Generated by Django 3.1.2 on 2020-11-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0011_auto_20201102_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destino', to='inv.sala')),
                ('objeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.objeto')),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origen', to='inv.sala')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.tipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
